---
- name: Creating backup folder for environment
  sudo: yes
  file:
    path: "{{ webroot }}/backup/{{ env }}"
    state: directory

- name: Making regular backup
  sudo: yes
  mysql_db:
    name: "{{ item.value }}"
    state: dump
    target: "{{ webroot }}/backup/{{ env }}/{{ item.value }}.sql.gz"
    login_user: "{{ mysql.user }}"
    login_password: "{{ mysql.pass }}"
  with_dict: databases

# @TODO Make import from remote!
