---
commands:
  pre:
    - en: [stage_file_proxy, security_review, dblog, devel, diff]
  post: []

drupal:
  # Settings of "Domain Access" module.
  domain:
    # Needed to use it's settings.inc inside of settings.php.
    path: "profiles/{{ profile }}/modules/contrib/domain"
  # Values for $conf in settings.php.
  conf:
    environment: "{{ env }}"
  # Variables in settings.php.
  settings:
    base_url: "{{ site_url }}"
  # Variables in database.
  variables:
    file_temporary_path: "{{ tmproot }}"
    error_level: 2
  # Data for super-admin (UID 1).
  user:
    name: admin
    pass: propeople
