---
- name: Ensure that NAT rule does not exists
  include: ../vboxmanage.yml
  args:
    command: "modifyvm {{ vm_name }} --natpf1 delete {{ item.key }}"
  ignore_errors: yes

- name: NAT port forwarding
  set_fact:
    vm_natpf: "{{ item.value.split(':') }}"

- name: Configure port forwarding for a new VM
  include: ../vboxmanage.yml
  args:
    # Scheme: [<name>],tcp|udp,[<hostip>],<hostport>,[<guestip>],<guestport>
    command: "modifyvm {{ vm_name }} --natpf1 '{{ item.key }},tcp,{{ vm_natpf | first }},{{ vm_natpf | last }}{{ vm_num }},,{{ vm_natpf | last }}'"
