---
- name: Set directory for extensions
  set_fact:
    vbox_extensions_dir: /root/vbox/extensions

- name: Ensure that directory for extensions exists
  file:
    path: "{{ vbox_extensions_dir }}"
    state: directory
    recurse: yes

- name: Download extension
  get_url:
    url: "{{ item }}"
    dest: "{{ vbox_extensions_dir }}/{{ item | basename }}"
  with_items: "{{ virtualbox.extensions }}"

- name: Install extension
  shell: "VBoxManage extpack install {{ vbox_extensions_dir }}/{{ item | basename }}"
  with_items: "{{ virtualbox.extensions }}"
