# WARNING! This file is not managed by Ansible and should not contain any usage of it features.
---
tmproot: /tmp
webroot: /var/www
selenium: http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar
APPLICATION_CONFIG: ~
vm:
  ip: 192.168.56.132
  forwarded_port:
    - host: 8081
      guest: 80
    - host: 8083
      guest: 3306
    - host: 4444
      guest: 4444
  virtualbox:
    box: http://cici.ffwua.com/ubuntu14.04LTS_cibox.box
    modifyvm:
      cpus: 2
      memory: 2048
      natdnshostresolver1: "on"
  lxc:
    box: http://cici.ffwua.com/ubuntu14.04provisionedCIBox.lxc.box
  synced_folder:
    - source: ./
      target: /var/www
      exclude:
        - .idea/
        - .git/
