# WARNING! This file is not managed by Ansible and should not contain any usage of it features.
---
tmproot: /tmp
webroot: /var/www
vm:
  ip: 192.168.56.132
  forwarded_port:
    CocLsFE7aIwA:
      host: 8081
      guest: 80
    CocLsFE7aIwE:
      host: 8083
      guest: 3306
  virtualbox:
    box: http://128.199.55.125/ubuntu14.04LTS_cibox.box
    modifyvm:
      cpus: 2
      memory: 2048
      natdnshostresolver1: "on"
  lxc:
    box: https://atlas.hashicorp.com/fgrehm/boxes/precise64-lxc/versions/1.2.0/providers/lxc.box
  synced_folder:
    - source: ./
      target: /var/www
      exclude:
        - .idea/
        - .git/
