---
- name: Set accesses for directories
  file:
    mode: 0777
    dest: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ tmproot }}"
    - "{{ webroot }}/backup"
    - "{{ project_workspace }}/sites/default"

- name: Remove settings.php
  file:
    path: "{{ project_workspace }}/{{ settings }}"
    state: absent
