---
# https://github.com/propeoplemd/cibox/pull/349
- name: Recover from possible fail
  shell: dpkg --configure -a
  ignore_errors: yes

- name: Install APT repos
  apt_repository:
    repo: "{{ item }}"
    validate_certs: no
  with_items: apt_repos

- name: Update apt
  apt:
    update_cache: yes

- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: apt_packages
