---
- include_vars: xhprof.yml

- name: Ensure GraphViz is installed
  apt:
    name: graphviz
    state: installed

- name: Set XHProf configuration for specific PHP version
  set_fact:
    cibox_php_xhprof: "{{ cibox_php_xhprof[cibox_php_version.split('.') | first] }}"

- name: Clone XHProf repository
  git:
    repo: "{{ cibox_php_xhprof.repo }}"
    dest: /tmp/xhprof-repo
    version: "{{ cibox_php_xhprof.version }}"

- include: fixtures/compile.yml name="XHProf" dir="/tmp/xhprof-repo/extension"
