---
- hosts: localhost
  gather_facts: yes
  connection: local
  become: yes

  vars_files:
    - ../config.yml
    - vars/main.yml

  tasks:
    - name: Check existence of installation mode
      stat:
        path: "tasks/reinstall/{{ reinstall_mode }}.yml"
      register: is_reinstall_mode

    - name: Check existence of environment configuration
      stat:
        path: "vars/environments/{{ env }}.yml"
      register: is_env

    - include_vars: "vars/environments/{{ env if is_env.stat.exists else 'default' }}.yml"
    - include: "tasks/reinstall/{{ reinstall_mode if is_reinstall_mode.stat.exists else 'full' }}.yml"
    - include: "tasks/compass-compile.yml"
