---
- hosts: localhost
  connection: local
  gather_facts: yes
  sudo: yes

  vars_files:
   - ../../config.yml

  vars:
    # Varnish configuration.
    varnish_enabled: false
    # Use this secret in your client(Drupal Varnish module) in order to connect to Varnish.
    varnish_secret: "14bac2e6-1e34-4770-8078-974373b76c90"
    # SSL configuration.
    cibox_ssl_folder: /etc/apache/ssl
    # Apache configuration.
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_remove_default_vhost: true
    apache_mods_enabled:
      - rewrite.load
      - ssl.load
    apache_vhosts:
      - servername: "{{ site_url }}"
        documentroot: "{{ webroot }}/docroot"
    apache_vhosts_ssl:
      - servername: "{{ site_url }}"
        documentroot: "{{ webroot }}/docroot"
        certificate_file: "{{ cibox_ssl_folder }}/apache.crt"
        certificate_key_file: "{{ cibox_ssl_folder }}/apache.key"

  # Disable services to avoid conflicts in port usage.
  pre_tasks:
    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      with_items:
        - varnish
        - apache2

  roles:
    - role: cibox-varnish
      when: varnish_enabled

    - role: cibox-ssl-config
    - role: ansible-role-apache
