---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - ../../config.yml
    - vars/php.yml
    - vars/mysql.yml
    - vars/apache.yml

  vars:
    # Varnish configuration.
    varnish_enabled: false
    solr_enabled: true
    # Use this secret in your client(Drupal Varnish module) in order to connect to Varnish.
    varnish_secret: "14bac2e6-1e34-4770-8078-974373b76c90"
    # SSL configuration.
    cibox_ssl_folder: /etc/apache/ssl
    cibox_composer_drush:
      version: 6.*
      user: "{{ vm.ssh.username }}"

  pre_tasks:
    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      with_items:
        - varnish
        - apache2

  roles:
    - role: cibox-misc
      tags: ["misc"]

    - role: ansible-role-apache
      sudo: yes
      tags: ["apache", "php-stack"]

    - role: ansible-role-php
      sudo: yes
      tags: ["php-stack"]

    - role: ansible-php-pear
      tags: ["pear", "php-stack"]

    - role: ansible-role-php-xhprof
      sudo: yes
      tags: ["xhprof", "php-stack"]

    - role: ansible-role-php-xdebug
      sudo: yes
      tags: ["xdebug", "php-stack"]

    - role: ansible-composer
      sudo: yes
      tags: ["composer", "php-stack"]

    - role: cibox-composer-drush
      tags: ["composer", "php-stack", "drush"]

    - role: ansible-role-mysql
      sudo: yes
      tags: ["mysql", "php-stack", "ansible-role-mysql"]

    - role: cibox-jetty-solr
      sudo: yes
      when: solr_enabled
      tags: ["solr", "php-stack"]

    - role: cibox-sniffers
      tags: ["cibox-sniffers", "php-stack"]

    - role: cibox-mysql-config
      tags: ["mysql", "php-stack", "cibox-mysql-config"]

    - role: cibox-ssl-config
      sudo: yes

    - role: cibox-varnish
      sudo: yes
      when: varnish_enabled
      tags: ["varnish"]

    - role: ansible-role-memcached
      tags: ["memcache", "php-stack"]

  tasks:
    - name: Sendmail symlink
      file:
        src: /bin/true
        dest: /usr/sbin/sendmail
        state: link
