---
- name: Clone Git repos
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ composer_dir }}/vendor/conding-standards/{{ item.key }}"
    version: "{{ item.value.branch }}"
  with_dict: "{{ git_repos }}"

- name: Remove all registered PHP Conde Sniffer standards
  shell: "phpcs --config-delete installed_paths"

- name: Install PHP CodeSniffer standards
  shell: "phpcs --config-set installed_paths {{ composer_dir }}/vendor/conding-standards/{{ git_repos.keys() | join(',' + composer_dir + '/vendor/conding-standards/') }}"

- name: Install Node.js packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_packages }}"

- name: Update ruby alternatives for using ruby 1.9.1(3) version
  shell: "update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 --slave /usr/share/man/man1/ruby.1.gz ruby.1.gz /usr/share/man/man1/ruby1.9.1.1.gz --slave /usr/bin/ri ri /usr/bin/ri1.9.1 --slave /usr/bin/irb irb /usr/bin/irb1.9.1 --slave /usr/bin/rdoc rdoc /usr/bin/rdoc1.9.1"

- name: Install Gem packages
  shell: "gem install {{ item }}"
  with_items: "{{ gem_packages }}"
  ignore_errors: yes
