---
- name: settings.php
  shell: "cp default.settings.php settings.php"
  args:
    chdir: ../docroot/sites/default

- name: Generating settings
  become: no
  template:
    src: templates/settings.php.j2
    dest: ./settings.php
    mode: 0644

- name: Write settings.php
  lineinfile:
    dest: "../docroot/sites/default/settings.php"
    line: "{{ lookup('file', 'settings.php') }}"

- name: Remove temporary settings
  become: no
  file:
    path: settings.php
    state: absent

- name: Adding variables to settings.php
  lineinfile:
    dest: "../docroot/sites/default/settings.php"
    line: "${{ item.key }} = '{{ item.value }}';"
  with_dict: "{{ drupal.settings }}"

- name: Adding $conf values to settings.php
  lineinfile:
    dest: "../docroot/sites/default/settings.php"
    line: "$conf['{{ item.key }}'] = '{{ item.value }}';"
  with_dict: "{{ drupal.conf }}"
