---
- name: Create config
  copy:
    src: "{{ phpvirtualbox.path }}/config.php-example"
    dest: "{{ phpvirtualbox.path }}/config.php"

- name: Configure
  replace:
    dest: "{{ phpvirtualbox.path }}/config.php"
    regexp: '^var \${{ item.search }}.*;$'
    replace: "var ${{ item.search }} = '{{ item.replace }}';"
  with_dict:
    - search: "username"
      replace: "{{ phpvirtualbox.user.user }}"

    - search: "password"
      replace: "{{ phpvirtualbox.user.pass }}"

    - search: "vrdeports"
      replace: "9001-9100"

- name: Create user
  user:
    name: "{{ phpvirtualbox.user.user }}"
    password: "{{ phpvirtualbox.user.pass }}"

- name: Configure VBoxWeb user
  template:
    src: phpvirtualbox.j2
    dest: /etc/default/virtualbox
