---
- name: Configure PHP-FPM to work via UNIX socket
  replace:
    dest: /etc/php5/fpm/pool.d/www.conf
    regexp: "^listen.*sock$"
    replace: "listen={{ php_fpm.socket }}"

- name: Start service and enable it on a boot
  service:
    name: php5-fpm
    state: restarted
    enabled: yes
