---
droplet_add: no
droplet_list: no
droplet_delete: ""
virtualmachine:
  path: "/home/{{ phpvirtualbox.user.user }}/VirtualBox\\ VMs/initvm"
  package: "http://propeople.com.ua/ffw_ubuntu_14.04LTS_minimal.tar.gz"
  port_forwarding:
    22:
      vhost: no
      ssl: no
    80:
      vhost: yes
      ssl: no
    443:
      vhost: yes
      ssl: yes
