---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # As name of folder inside of "cmf/".
    cmf: "drupal"
    # As name of folder inside of "cmf/<NAME>/"
    version: "7.51"
    # Host for cloning repository from.
    host: "https://github.com"
    without_sources: no

  vars_files:
    - ../config.yml

  tasks:
    - include: tasks/project-variable.yml

    - name: Determine major version of CMF
      set_fact:
        major: "{{ version.split('.') | first }}"

    - name: Check for CMF configuration
      stat:
        path: "../cmf/{{ cmf }}/{{ major | int }}"
      register: cmf_configs

    - name: CMF is not available
      fail:
        msg: "You are not allowed to install {{ cmf | capitalize }} {{ version }} because it isn't pre-configured."
      when: not cmf_configs.stat.exists

    - name: Downloading CMF
      git:
        dest: "../{{ project }}/docroot"
        repo: "{{ host }}/{{ vendor if vendor is defined else cmf }}/{{ cmf }}.git"
        version: "{{ version }}"
      when: "{{ not without_sources }}"

    - name: Prepare CIBox-structured repository
      synchronize:
        src: "{{ item.src }}"
        dest: "../{{ project }}/{{ item.dest | default('') }}"
        archive: no
        recursive: yes
      with_items:
        - src: "../cmf/all/"
        - src: "../cmf/{{ cmf }}/all/"
        - src: "{{ cmf_configs.stat.path }}/"
        - src: "../cibox"
        - src: "../config.yml"
        - src: "../inventory"

        - src: "../scripts/"
          dest: "provisioning"

    - name: Clear created repository
      file:
        path: "../{{ project }}/{{ item }}"
        state: absent
      with_items:
        - provisioning/repository.yml
        - docroot/.gitignore
        - docroot/.git
        - APPLICATION_CONFIG.yml

    - name: Setting permissions for project tree
      file:
        mode: 0777
        path: "../{{ project }}"
        state: directory
        recurse: yes

    - name: Update config.yml
      lineinfile:
        dest: "../{{ project }}/config.yml"
        line: "cmf: {{ cmf }}\ncore: {{ major }}\nproject: {{ project }}\nsite_url: https://{{ project }}.dev"
        insertafter: "^---$"

    - name: Update config.yml
      replace:
        dest: "../{{ project }}/config.yml"
        regexp: "APPLICATION_CONFIG: ~"
        replace: "{{ lookup('file', cmf_configs.stat.path + '/APPLICATION_CONFIG.yml') }}"
