---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # As name of folder inside of "cmf/".
    cmf: drupal
    # As name of folder inside of "cmf/<NAME>/"
    version: 7.41
    # Host for cloning repository from.
    host: https://github.com
    # Part of namespace on a host (vendor name).
    vendor: drupal
    adminer: 4.2.2

  vars_files:
    - ../config.yml

  tasks:
    - include: tasks/project-variable.yml

    - name: Determine major version of CMF
      set_fact:
        major: '{{ version | regex_replace("^(\d).*$", "\\1") }}'

    - name: Check for CMF configuration
      stat:
        path: "../cmf/{{ cmf }}/{{ major }}/"
      register: cmf_configs

    - name: CMF is not available
      fail:
        msg: "You are not allowed to install {{ cmf | major }} {{ version }} because it isn't pre-configured."
      when: not cmf_configs.stat.exists

    - name: Downloading CMF
      git:
        dest: "../{{ project }}/docroot"
        repo: "{{ host }}/{{ vendor }}/{{ cmf }}.git"
        version: "{{ version }}"

    - name: Downloading Adminer.php
      get_url:
        url: "https://www.adminer.org/static/download/{{ adminer }}/adminer-{{ adminer }}-en.php"
        dest: "../{{ project }}/adminer.php"
      when: adminer != "none"

    - name: Prepare CIBox-structured repository
      synchronize:
        src: "{{ item.src }}"
        dest: "../{{ project }}/{{ item.dest | default('') }}"
        archive: no
        recursive: yes
      with_items:
        - src: "{{ cmf_configs.stat.path }}/"
        - src: "../ansible.sh"
        - src: "../config.yml"
        - src: "../inventory"
        - src: "../vagrant/"

        - src: "../scripts/"
          dest: "provisioning"

    - name: Clear created repository
      file:
        path: "../{{ project }}/{{ item }}"
        state: absent
      with_items:
        - provisioning/repository.yml

    - name: Setting permissions for project tree
      file:
        mode: 0777
        path: "../{{ project }}"
        state: directory
        recurse: yes

    - name: Add Vagrant host to inventory file
      lineinfile:
        dest: "../{{ project }}/inventory"
        line: "\n[vagrant]\n{{ vm.network.private_network }} ansible_ssh_user={{ vm.ssh.username }} ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key"

    - name: Set name of the project to config.yml
      lineinfile:
        dest: "../{{ project }}/config.yml"
        line: "project: {{ project }}\nsite_url: http://{{ project }}.dev"
        insertafter: "^---$"
