---
- hosts: all
  gather_facts: yes
#  become: yes

  vars_files:
    - vars/php.yml
    - vars/ports.yml
    - vars/mysql.yml
    - vars/nginx.yml
    - vars/apache.yml

  vars:
    restart: ""

  tasks:
    - name: Restart service
      service:
        name: "{{ item }}"
        state: restarted
      with_items: "{{ restart.split(',') }}"
      when: "{{ restart | length > 0 }}"
      tags: ["always"]
