---
- include: repo.yml

- name: Download Jenkins
  get_url:
    url: "{{ jenkins_pkg_version }}"
    dest: ~/jenkins.deb
    mode: 440

- name: Create default config
  template:
    src: jenkins.j2
    dest: /etc/default/jenkins

- name: Install Jenkins
  shell: "dpkg -i ~/jenkins.deb"

- name: Restart service
  service:
    name: jenkins
    state: restarted

- include: cli.yml

- name: Install/update plugins
  shell: "java -jar {{ jenkins.cli_dest }} -s {{ jenkins_host }} install-plugin {{ item }}"
  with_items: "{{ plugins }}"
  notify: Restart Jenkins

- name: Restore service
  service:
    name: "{{ item }}"
    state: started
  ignore_errors: yes
  with_items: ["nginx", "apache2"]

- name: Adding Jenkins user to permitted groups
  user:
    name: "{{ jenkins_data.user }}"
    groups: shadow,adm
    append: yes

- name: Adding Jenkins user to nopasswd sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ jenkins_data.user }} ALL=(ALL) NOPASSWD:ALL"

- include: configure.yml
