---
- name: Remove database
  include: ../database/database.yml
  args:
    state: absent

- name: Create config
  template:
    src: templates/wp-config.j2
    dest: ../docroot/wp-config.php

- name: Create database
  include: ../database/database.yml
  args:
    state: present

- include: ../wp-cli/core-install.yml
  when: not sql_workflow

# Download and import databases.
- include: ../database/import.yml
  when: sql_workflow

# Unique way for both workflows.
- include: ../super-admin.yml

# Enable/disable configured plugins.
- include: ../wp-cli/plugins.yml
- include: ../wp-cli/commands.yml
