---
- hosts: localhost
  gather_facts: yes
  connection: local
  sudo: yes

  vars_files:
    - ../provisioning/config.yml
    - vars/main.yml

  tasks:
    - include_vars: "vars/environments/{{ env }}.yml"

    - include: tasks/database/remove.yml
    - include: tasks/prepare-environment.yml

    - include: tasks/drush/si.yml
      when: not sql_workflow

    - include: tasks/database/create.yml
    - include: tasks/drupal-settings.yml

    # Download and import databases.
    - include: tasks/database/import.yml
      when: sql_workflow

    # Unique way for both workflows.
    - include: tasks/super-admin.yml

    - include: tasks/drush/rr.yml
      when: sql_workflow

    - include: tasks/drush/vset.yml

    # Enable/disable configured modules.
    - include: tasks/drush/modules.yml

    - include: tasks/drush/updb.yml
      when: sql_workflow

    - include: tasks/drush/features.yml
      when: sql_workflow

    - include: tasks/drush/commands.yml
