---
- hosts: localhost
  gather_facts: yes
  connection: local
  sudo: yes

  vars_files:
    - ../config.yml
    - vars/main.yml
    - vars/tests.yml

  vars:
    run: no
    service_args: "-role hub -log selenium.log"

  pre_tasks:
    - name: Check if Behat is already installed
      stat:
        path: ../vendor/behat/behat/
      register: behat_state

    - name: Install Behat
      shell: cd ../ && composer install
      when: not behat_state.stat.exists

  tasks:
    - name: Ensure Selenium service started
      shell: "service selenium restart {{ service_args }}"

    - name: Wait for establish Selenium connection
      wait_for:
        port: 4444
        host: 127.0.0.1
        delay: 10

    - name: Create behat.yml
      template:
        src: templates/behat.j2
        dest: ../tests/behat/behat.yml

    - name: Run Behat tests
      shell: "cd ../tests/behat && ../../bin/behat"
      ignore_errors: yes
      when: run

    - include: tasks/reports-url.yml
      when: run

    - name: Create Behat report
      shell: 'if [ -s {{ reports_dir }}/behat/index.html ]; then echo "<a href=\"{{ reports_url }}/behat/index.html\" target=\"_blank\">Behat report</a>" >> {{ artifacts_file }}; fi'
      when: run
