---
- hosts: localhost
  gather_facts: yes
  connection: local
  become: yes

  vars_files:
    - ../config.yml
    - vars/main.yml
    - vars/tests.yml

  vars:
    run: no
    headless: no
    selenium_hub: yes

  pre_tasks:
    - name: Check if Behat is already installed
      stat:
        path: ../vendor/behat/behat/
      register: vendor_state

    - name: Check for composer.json
      stat:
        path: ../composer.json
      register: composer_json_state

    - name: Install Behat
      shell: cd ../ && composer install
      when: not vendor_state.stat.exists and composer_json_state.stat.exists

  tasks:
    - name: Ensure Xvfb service started
      service:
        name: xvfb
        state: started
        args: :99 -ac -screen 0 1024x768x24
      when: headless

    - name: Ensure Selenium service started
      service:
        name: selenium
        state: started
        args: "{{ '-role hub' if selenium_hub | bool else '' }} -log selenium.log"
      environment:
        DISPLAY: "{{ ':99' if headless | bool else '' }}"

    - name: Wait for establish Selenium connection
      wait_for:
        port: 4444
        host: 127.0.0.1
        delay: 10

    - name: Create behat.yml
      template:
        src: templates/behat.j2
        dest: ../tests/behat/behat.yml

    - name: Run Behat tests
      shell: "cd ../tests/behat && ../../bin/behat"
      ignore_errors: yes
      when: run

    - include: tasks/reports-url.yml
      when: run

    - name: Create Behat report
      shell: 'if [ -s {{ reports_dir }}/behat/index.html ]; then echo "<a href=\"{{ reports_url }}/behat/index.html\" target=\"_blank\">Behat report</a>" >> {{ artifacts_file }}; fi'
      when: run
