---
- include: theme-default.yml

- name: Get path to active theme
  shell: "drush dd {{ theme_default.stdout }}"
  args:
    chdir: "{{ project_workspace }}"
  register: theme_path

- name: Check for SCSS
  stat:
    path: "{{ project_workspace }}/{{ theme_path.stdout }}/config.rb"
  register: config_rb

- name: Compile SCSS
  become: no
  shell: "compass compile {{ theme_path.stdout }} --force"
  args:
    chdir: "{{ project_workspace }}"
  when: config_rb.stat.exists
